package org.davesEnterprise;

import org.davesEnterprise.download.DownloaderBuilder;
import org.davesEnterprise.enums.CurrentState;
import org.davesEnterprise.enums.SegmentValidation;
import org.davesEnterprise.util.Args;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

public class Gui extends JPanel {
    public JPanel mainPanel;

    public JTextArea uri;
    public JTextField outputName;

    public JSpinner downloads;
    public JSpinner validations;
    public JSpinner retries;

    public JComboBox<SegmentValidation> validationType;

    public JProgressBar progressDownload;
    public JProgressBar progressValidation;
    public JLabel currentState;

    public JButton logButton;
    public boolean showLog = false;
    public JTextArea logs;
    public JScrollPane logs_scrollPane;

    public JButton start;
    public JTextField workingDir;
    public JScrollPane uri_scrollPane;
    private JCheckBox keepSegmentsCheckBox;


    public Gui() {
        this.downloads.setValue(Args.get().concurrentDownloads);
        this.validations.setValue(Args.get().concurrentValidations);
        this.retries.setValue(Args.get().retries);

        this.workingDir.setText(String.valueOf(defaultWorkingDir()));

        this.validationType.setModel(new DefaultComboBoxModel<>(SegmentValidation.values()));
        this.validationType.setSelectedItem(SegmentValidation.DECODE);

        this.currentState.setText(CurrentState.IDLE.toString());
        this.logs_scrollPane.setVisible(this.showLog);

        this.start.addActionListener(this::start);
        this.logButton.addActionListener(this::logButtonPressed);
    }

    public void logButtonPressed(ActionEvent actionEvent) {
        this.showLog = !this.showLog;
        this.logs_scrollPane.setVisible(this.showLog);
        this.logButton.setText(this.showLog ? "Hide Log" : "Show Log");
    }

    private static Path defaultWorkingDir() {
        return Path.of(System.getProperty("user.home"), "Downloads");
    }

    private void start(ActionEvent actionEvent) {
        Path workingDir;
        if (!this.workingDir.getText().isBlank()) {
            workingDir = Path.of(this.workingDir.getText());
        } else {
            workingDir = defaultWorkingDir();
        }

        String outputName = this.outputName.getText().isBlank() ? DownloaderBuilder.getCurrentDateTime() : this.outputName.getText();

        CompletableFuture.runAsync(() ->
                new DownloaderBuilder(workingDir.resolve(outputName), this)
                        .setPlaylist(this.uri.getText())
                        .setSegmentValidation((SegmentValidation) this.validationType.getSelectedItem())
                        .setConcurrentDownloads((Integer) this.downloads.getValue())
                        .setConcurrentValidations((Integer) this.validations.getValue())
                        .setRetries((Integer) this.retries.getValue())
                        .setKeepSegments(this.keepSegmentsCheckBox.isSelected())
                        .build().start()
        ).thenRun(() -> SwingUtilities.invokeLater(() -> this.start.setEnabled(true)));
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(1006, 295));
        validations = new JSpinner();
        validations.setToolTipText("The number of (virtual-)threads for the segment validations. I.e., how many segments are validated in parallel.");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(validations, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Concurrent Validations:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Retries:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("The URI to the M3U8 HLS playlist: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label3, gbc);
        outputName = new JTextField();
        outputName.setToolTipText("The name of the output folder and video file. Dont specify the video extension.");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(outputName, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Output Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label4, gbc);
        progressDownload = new JProgressBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 12;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(progressDownload, gbc);
        progressValidation = new JProgressBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 14;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(progressValidation, gbc);
        start = new JButton();
        start.setText("Start!");
        start.setToolTipText("Start the download!");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 15;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(start, gbc);
        retries = new JSpinner();
        retries.setToolTipText("How often the download of a segment should be retried in case of network errors.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(retries, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Concurrent Downloads:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label5, gbc);
        downloads = new JSpinner();
        downloads.setToolTipText("The number of (virtual-)threads for the segment downloads. I.e., how many segments are downloaded in parallel.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(downloads, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Download:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 11;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Validation:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 13;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label7, gbc);
        validationType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("None");
        defaultComboBoxModel1.addElement("Metadata");
        defaultComboBoxModel1.addElement("Metadata + Decode");
        validationType.setModel(defaultComboBoxModel1);
        validationType.setToolTipText("The type of validation run for each segment. If a segment appears to be corrupt, it will be re-downloaded.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(validationType, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Segment Validation:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label8, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer4, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Working Dir:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label9, gbc);
        workingDir = new JTextField();
        workingDir.setText("");
        workingDir.setToolTipText("The parent directory in which the output folder will be placed.");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(workingDir, gbc);
        currentState = new JLabel();
        currentState.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 10;
        mainPanel.add(currentState, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer5, gbc);
        logButton = new JButton();
        logButton.setText("Show Log");
        logButton.setToolTipText("Whether to show the application log");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(logButton, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 18;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer6, gbc);
        logs_scrollPane = new JScrollPane();
        logs_scrollPane.setAutoscrolls(true);
        logs_scrollPane.setMinimumSize(new Dimension(200, 100));
        logs_scrollPane.setOpaque(true);
        logs_scrollPane.setPreferredSize(new Dimension(200, 100));
        logs_scrollPane.setVerticalScrollBarPolicy(22);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 17;
        gbc.gridwidth = 4;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(logs_scrollPane, gbc);
        logs = new JTextArea();
        logs.setEditable(false);
        logs.setEnabled(true);
        logs.setText("");
        logs_scrollPane.setViewportView(logs);
        uri_scrollPane = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(uri_scrollPane, gbc);
        uri = new JTextArea();
        uri.setLineWrap(true);
        uri.setMaximumSize(new Dimension(2147483647, 200));
        uri.setText("");
        uri.setToolTipText("The URI to the M3U8 HLS playlist. E.g., https://www.example.com/video/playlist.m3u8");
        uri.setWrapStyleWord(false);
        uri_scrollPane.setViewportView(uri);
        keepSegmentsCheckBox = new JCheckBox();
        keepSegmentsCheckBox.setText("Keep Segments");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(keepSegmentsCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
